/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.src.frontend;

/**
 *
 * @author User
 */
public class ViewRecords extends javax.swing.JFrame {

    /**
     * Creates new form ViewRecords
     */
    public ViewRecords() {
        initComponents();
        // try {
        //     for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        //         if ("Nimbus".equals(info.getName())) {
        //             javax.swing.UIManager.setLookAndFeel(info.getClassName());
        //             break;
        //         }
        //     }
        // } catch (ClassNotFoundException ex) {
        //     java.util.logging.Logger.getLogger(ViewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        // } catch (InstantiationException ex) {
        //     java.util.logging.Logger.getLogger(ViewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        // } catch (IllegalAccessException ex) {
        //     java.util.logging.Logger.getLogger(ViewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        // } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        //     java.util.logging.Logger.getLogger(ViewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        // }
        setLocationRelativeTo(null);
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        evaluatorLine2D1 = new org.jdesktop.swing.animation.timing.evaluators.EvaluatorLine2D();
        evaluatorQuadCurve2D1 = new org.jdesktop.swing.animation.timing.evaluators.EvaluatorQuadCurve2D();
        evaluatorLong1 = new org.jdesktop.core.animation.timing.evaluators.EvaluatorLong();
        evaluatorDouble1 = new org.jdesktop.core.animation.timing.evaluators.EvaluatorDouble();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        date_fromDate = new rojeru_san.componentes.RSDateChooser();
        jLabel3 = new javax.swing.JLabel();
        date_toDate = new rojeru_san.componentes.RSDateChooser();
        searchButton2 = new rojerusan.RSButtonHover();
        backButton = new rojeru_san.complementos.RSButtonHover();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_issueBookDetails = new rojeru_san.complementos.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(47, 120, 152));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 230));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(220, 238, 229));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/BookIDIcon.png"))); // NOI18N
        jLabel1.setText("View Records");
        jLabel1.setIconTextGap(0);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 470, 150));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(220, 238, 229));
        jLabel2.setText("From");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 50, 40));

        date_fromDate.setColorBackground(new java.awt.Color(3, 47, 90));
        date_fromDate.setColorButtonHover(new java.awt.Color(5, 77, 120));
        date_fromDate.setColorDiaActual(new java.awt.Color(255, 255, 255));
        date_fromDate.setColorForeground(new java.awt.Color(3, 47, 90));
        date_fromDate.setColorTextDiaActual(new java.awt.Color(0, 0, 0));
        date_fromDate.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        date_fromDate.setFormatoFecha("dd/MM/yyyy");
        date_fromDate.setPlaceholder("Select Issue Date");
        jPanel1.add(date_fromDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(220, 238, 229));
        jLabel3.setText("To");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 30, 40));

        date_toDate.setColorBackground(new java.awt.Color(3, 47, 90));
        date_toDate.setColorButtonHover(new java.awt.Color(5, 77, 120));
        date_toDate.setColorDiaActual(new java.awt.Color(255, 255, 255));
        date_toDate.setColorForeground(new java.awt.Color(3, 47, 90));
        date_toDate.setColorTextDiaActual(new java.awt.Color(0, 0, 0));
        date_toDate.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        date_toDate.setFormatoFecha("dd/MM/yyyy");
        date_toDate.setPlaceholder("Select Issue Date");
        jPanel1.add(date_toDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, -1));

        searchButton2.setBackground(new java.awt.Color(3, 47, 90));
        searchButton2.setBorder(null);
        searchButton2.setForeground(new java.awt.Color(220, 238, 229));
        searchButton2.setText("Search");
        searchButton2.setColorHover(new java.awt.Color(5, 77, 120));
        searchButton2.setColorText(new java.awt.Color(220, 238, 229));
        jPanel1.add(searchButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 140, -1));

        backButton.setBackground(new java.awt.Color(3, 47, 90));
        backButton.setForeground(new java.awt.Color(220, 238, 229));
        backButton.setText("Back");
        backButton.setColorHover(new java.awt.Color(5, 77, 120));
        backButton.setColorText(new java.awt.Color(220, 238, 229));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new HomePage();
                setVisible(false);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 239));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_issueBookDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "A", "Duc", "16/11/2024", "1/12025", "pending"},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Book", "Student", "Issue Date", "Due Date", "Status"
            }
        ));
        tbl_issueBookDetails.setColorBackgoundHead(new java.awt.Color(47, 120, 152));
        tbl_issueBookDetails.setColorBordeFilas(new java.awt.Color(47, 120, 152));
        tbl_issueBookDetails.setColorBordeHead(new java.awt.Color(220, 238, 229));
        tbl_issueBookDetails.setColorFilasBackgound1(new java.awt.Color(220, 238, 229));
        tbl_issueBookDetails.setColorFilasBackgound2(new java.awt.Color(220, 238, 229));
        tbl_issueBookDetails.setColorFilasForeground1(new java.awt.Color(47, 120, 152));
        tbl_issueBookDetails.setColorFilasForeground2(new java.awt.Color(47, 120, 152));
        tbl_issueBookDetails.setColorForegroundHead(new java.awt.Color(220, 238, 229));
        tbl_issueBookDetails.setColorSelBackgound(new java.awt.Color(3, 47, 90));
        tbl_issueBookDetails.setColorSelForeground(new java.awt.Color(124, 182, 192));
        tbl_issueBookDetails.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_issueBookDetails.setRowHeight(42);
        tbl_issueBookDetails.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_issueBookDetails);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 770, 350));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 1000, 400));

        setSize(new java.awt.Dimension(1016, 648));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    //     /* Set the Nimbus look and feel */
    //     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    //     /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    //      * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    //      */
    //     try {
    //         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //             if ("Nimbus".equals(info.getName())) {
    //                 javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                 break;
    //             }
    //         }
    //     } catch (ClassNotFoundException ex) {
    //         java.util.logging.Logger.getLogger(ViewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (InstantiationException ex) {
    //         java.util.logging.Logger.getLogger(ViewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (IllegalAccessException ex) {
    //         java.util.logging.Logger.getLogger(ViewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //         java.util.logging.Logger.getLogger(ViewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     }
    //     //</editor-fold>

    //     /* Create and display the form */
    //     java.awt.EventQueue.invokeLater(new Runnable() {
    //         public void run() {
    //             new ViewRecords().setVisible(true);
    //         }
    //     });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSButtonHover backButton;
    private rojeru_san.componentes.RSDateChooser date_fromDate;
    private rojeru_san.componentes.RSDateChooser date_toDate;
    private org.jdesktop.core.animation.timing.evaluators.EvaluatorDouble evaluatorDouble1;
    private org.jdesktop.swing.animation.timing.evaluators.EvaluatorLine2D evaluatorLine2D1;
    private org.jdesktop.core.animation.timing.evaluators.EvaluatorLong evaluatorLong1;
    private org.jdesktop.swing.animation.timing.evaluators.EvaluatorQuadCurve2D evaluatorQuadCurve2D1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSButtonHover searchButton2;
    private rojeru_san.complementos.RSTableMetro tbl_issueBookDetails;
    // End of variables declaration//GEN-END:variables
}
