/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.src.frontend;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

import javax.swing.JFrame;

/**
 *
 * @author User
 */
public class ViewIssuedBooks extends javax.swing.JFrame {

    /**
     * Creates new form ViewIssuedBooks
     */
    public ViewIssuedBooks() {
        setPreferredSize(new Dimension(1100, 640));
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setResizable(false);
        setLayout(new BorderLayout());
        
        initComponents();
        pack();
        setVisible(true);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_issueBookDetails = new rojeru_san.complementos.RSTableMetro();
        backButton = new rojeru_san.complementos.RSButtonHover();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(3, 47, 90));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/BookNameIcon.png"))); // NOI18N
        jLabel1.setText("Issued Books");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 370, 90));

        tbl_issueBookDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "A", "Duc", "16/11/2024", "1/12025", "pending"},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Book", "Student", "Issue Date", "Due Date", "Status"
            }
        ));
        tbl_issueBookDetails.setColorBackgoundHead(new java.awt.Color(47, 120, 152));
        tbl_issueBookDetails.setColorBordeFilas(new java.awt.Color(47, 120, 152));
        tbl_issueBookDetails.setColorBordeHead(new java.awt.Color(220, 238, 229));
        tbl_issueBookDetails.setColorFilasBackgound1(new java.awt.Color(220, 238, 229));
        tbl_issueBookDetails.setColorFilasBackgound2(new java.awt.Color(220, 238, 229));
        tbl_issueBookDetails.setColorFilasForeground1(new java.awt.Color(47, 120, 152));
        tbl_issueBookDetails.setColorFilasForeground2(new java.awt.Color(47, 120, 152));
        tbl_issueBookDetails.setColorForegroundHead(new java.awt.Color(220, 238, 229));
        tbl_issueBookDetails.setColorSelBackgound(new java.awt.Color(3, 47, 90));
        tbl_issueBookDetails.setColorSelForeground(new java.awt.Color(124, 182, 192));
        tbl_issueBookDetails.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_issueBookDetails.setRowHeight(42);
        tbl_issueBookDetails.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_issueBookDetails);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 770, 350));

        backButton.setBackground(new java.awt.Color(3, 47, 90));
        backButton.setForeground(new java.awt.Color(220, 238, 229));
        backButton.setText("Back");
        backButton.setColorHover(new java.awt.Color(5, 77, 120));
        backButton.setColorText(new java.awt.Color(220, 238, 229));

        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new HomePage();
                setVisible(false);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSButtonHover backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.complementos.RSTableMetro tbl_issueBookDetails;
    // End of variables declaration//GEN-END:variables
}
